### ISSUE TITLE
change points not robust

### ISSUE THREAD

**Issue by StuartLittlefair** [martinmcallister/lfit_python#5]
Martin - the following code

``` python
def createGP(params,phi):
    a, tau = np.exp(params[:2])
    dphi, phiOff = params[7],params[15]

    k_out = a*GP.Matern32Kernel(tau)
    k_in  = 0.01*a*GP.Matern32Kernel(tau)

    changepoints = [-dphi/2., dphi/2.]
```

will only work when the data go from phi=-0.5 to phi=0.5 or similar. We need more robust code which detects all the change points, just in case we use an eclipse where phi goes from 0.8 to 1.2, or a data file which has two eclipses, and so on.

**Comment by martinmcallister** [comment]
Ah yes, I'll have a go at improving the code to take into account different changepoint positions.

**Comment by martinmcallister** [comment]
Hi Stu,

I've made the following changes to mcmcfit.py to accommodate for multiple
eclipses and non-zero Tmids:

def createGP(params,phi):
    a, tau = np.exp(params[:2])
    dphi, phiOff = params[7],params[15]

```
k_out = a*GP.Matern32Kernel(tau)
k_in  = 0.001*a*GP.Matern32Kernel(tau)

changepoints = [-dphi/2.,dphi/2.,1-dphi/2.,1+dphi/2.] # in case of Tmid
```

= 1 or multiple eclipses

```
# create kernel with changepoints
# obviously need one more kernel than changepoints!
kernel =
```

GP.DrasticChangepointKernel([k_out,k_in,k_out,k_in,k_out],changepoints)
#final two kernels allow multiple eclipses to be fit

```
# create GPs using this kernel
gp = GP.GaussianProcess(kernel)
return gp
```

I initially spent some time altering the GaussianProcess.py code, as I
thought this would be a more elegant way of incorporating the different
types of eclipse, but struggled to find a way of going about this. I can
give this another go, but may need a few pointers to get me started.

Are you free at some point this afternoon or tomorrow to have a chat about
where I'm currently at, in both the code and otherwise?

Cheers,
Martin

**Comment by StuartLittlefair** [comment]
Hi Martin,

Maybe we need to chat about this, but sadly I'm busy all today and leave
for hawaii tonight.
What you've done won't work for the general case, and adds more kernels
than we need when there's only one eclipse. However, you're making changes
in the right place.

When coding, you have to come up with an algorithm, or pseudo code, that
solves the problem, and then implement it. It seems you're struggling with
the first step, which is problem solving rather than coding!

The pseudo-code I had in mind is something like:

1) look at x-array in data and find the points when WD mid eclipse occurs...

  this would be at phases of -dphi/2 and dphi/2, plus -dphi/2 + n and
dphi/2 +n,
  for all n = -infty, ..., -2, -1, 0, 1, 2, ...

  this is the fiddly stage, and you need to think carefully about how to
code this up.
  the modulus mathematical operator might be some help

  this stage will ideally leave you with a python list of all change points

2) create the kernel array from the list of change points.

  You might only have two, or six, or eighty, but you need an automated way
of filling a list
  with k_in or k_out as appropriate

The rest of your code would be fine, with the kernel initialised with the
two lists produced by the steps above.

Stu

On 9 June 2015 at 11:40, martinmcallister notifications@github.com wrote:

> Hi Stu,
> 
> I've made the following changes to mcmcfit.py to accommodate for multiple
> eclipses and non-zero Tmids:
> 
> def createGP(params,phi):
> a, tau = np.exp(params[:2])
> dphi, phiOff = params[7],params[15]
> 
> k_out = a_GP.Matern32Kernel(tau)
> k_in = 0.001_a*GP.Matern32Kernel(tau)
> 
> changepoints = [-dphi/2.,dphi/2.,1-dphi/2.,1+dphi/2.] # in case of Tmid
> = 1 or multiple eclipses
> 
> # create kernel with changepoints
> 
> # obviously need one more kernel than changepoints!
> 
> kernel =
> GP.DrasticChangepointKernel([k_out,k_in,k_out,k_in,k_out],changepoints)
> #final two kernels allow multiple eclipses to be fit
> 
> # create GPs using this kernel
> 
> gp = GP.GaussianProcess(kernel)
> return gp
> 
> I initially spent some time altering the GaussianProcess.py code, as I
> thought this would be a more elegant way of incorporating the different
> types of eclipse, but struggled to find a way of going about this. I can
> give this another go, but may need a few pointers to get me started.
> 
> Are you free at some point this afternoon or tomorrow to have a chat about
> where I'm currently at, in both the code and otherwise?
> 
> Cheers,
> Martin
> 
> On 1 June 2015 at 14:18, Martin mmcallister1@sheffield.ac.uk wrote:
> 
> > Ah yes, I'll have a go at improving the code to take into account
> > different changepoint positions.
> > 
> > Sent from my iPhone
> > 
> > On 1 Jun 2015, at 12:59, StuartLittlefair notifications@github.com
> > wrote:
> > 
> > Martin - the following code
> > 
> > def createGP(params,phi):
> > a, tau = np.exp(params[:2])
> > dphi, phiOff = params[7],params[15]
> > 
> > k_out = a_GP.Matern32Kernel(tau)
> > k_in = 0.01_a*GP.Matern32Kernel(tau)
> > 
> > changepoints = [-dphi/2., dphi/2.]
> > 
> > will only work when the data go from phi=-0.5 to phi=0.5 or similar. We
> > need more robust code which detects all the change points, just in case
> > we
> > use an eclipse where phi goes from 0.8 to 1.2, or a data file which has
> > two
> > eclipses, and so on.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/martinmcallister/lfit_python/issues/5.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/martinmcallister/lfit_python/issues/5#issuecomment-110314388
> .

## 

Stuart Littlefair

---

Dept. of Physics & Astronomy,
Univ. of Sheffield, Sheffield, S3 7RH.

email: S.Littlefair@sheffield.ac.uk
phone: +44 114 2224525
